server:
  port: 8081

spring:
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/Tartlist/spring-ms-practice.git
          search-paths:
            - ConfigData
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}

  security:
    user:
      name: root
      password: s3cr3t
